### ISSUE TITLE
New feed: Inglewood I-Line Shuttle

### ISSUE THREAD

**Issue by julieteldred** [LACMTA/los-angeles-regional-gtfs#19]
Hi LACMTA folks - through Cal-ITP, Trillium created a feed for Inglewood's I-Line Shuttle system and wanted to add it to LACMTA's repository for long-term hosting/maintenance purposes. It didn't look like I could create a pull request (and I'm pretty bad at Github) but it looks like I can add a new Issue, so I figured I'd submit the feed this way (apologies if this isn't proper protocol). ZIP folder is attached here; let me know if you have any trouble accessing the file. If you have any further questions feel free to reach out to me at juliet@trilliumtransit.com/ 
[inglewoodshuttle-ca-us.zip](https://github.com/LACMTA/los-angeles-regional-gtfs/files/9426151/inglewoodshuttle-ca-us.zip)

thanks! - juliet

**Comment by matikin9** [comment]
Thanks! @julieteldred I'll get this added!
